// Palabras de 6-8 letras para el modo difícil
export const hardWords = [
  // Palabras de 6 letras
  'CABEZA', 'CENTRO', 'CAMINO', 'GRANDE', 'FUERTE', 'DENTRO', 'TIEMPO', 'PUEBLO', 
  'GUERRA', 'PUEBLO', 'MANERA', 'ESTADO', 'AUNQUE', 'MOMENTO', 'CIUDAD', 'VERDAD',
  'ESCUELA', 'TRABAJO', 'SISTEMA', 'EMPRESA', 'PROBLEMA', 'PROGRAMA', 'FAMILIA',
  
  // Palabras de 7 letras
  'EJEMPLO', 'SERVICIO', 'HISTORIA', 'PROCESO', 'ENERGIA', 'MATERIA', 'PERSONA',
  'SOCIEDAD', 'AMBIENTE', 'NACIONAL', 'GENERAL', 'NATURAL', 'POPULAR', 'SENTIDO',
  'CULTURA', 'TECNICO', 'ESPECIAL', 'PROYECTO', 'GOBIERNO', 'ARCHIVO', 'MUNDIAL',
  
  // Palabras de 8 letras
  'DESARROLLO', 'ESTRUCTURA', 'EDUCACION', 'TECNOLOGIA', 'INDUSTRIA', 'MEDICINA',
  'UNIVERSO', 'ECONOMIA', 'SOCIEDAD', 'PERSONAL', 'NACIONAL', 'TEMPORAL', 'ESPACIAL',
  'CONJUNTO', 'FUNCIONAL', 'ORGANIZACION', 'INVESTIGACION', 'COMUNICACION'
];