
export const words = [
  "abeto", "acero", "queso", "actor", "agudo", "aireo", "ajeno", "alado", "altar", "amado", "amigo", "murio",
    "andar", "ancho", "angel", "antes", "apoyo", "arado", "arena", "aroma", "asado", "asilo", "plata", "morir",
    "astro", "atado", "autor", "aviso", "ayuda", "azote", "banco", "barco", "bazar", "bebes", "cobro", 
    "bella", "besos", "blusa", "bocas", "borde", "bravo", "brota", "bueno", "burla", "cabra", "placa",
    "calor", "campo", "canal", "canto", "carro", "casas", "casco", "cielo", "cinta", "claro", "jefes",
    "clave", "coche", "colmo", "comer", "coral", "corte", "cruce", "cuota", "dardo", "dejar", "losas",
    "denso", "desde", "dieta", "digno", "diosa", "doble", "dolor", "drama", "duelo", "dulce", "lomas",
    "ecoar", "edito", "efebo", "ejote", "elote", "emana", "emite", "enano", "entra", "envio", "pasos",
    "epoca", "error", "esmal", "estar", "etapa", "exito", "extra", "falso", "fango", "feliz", "hasta",
    "firme", "flaco", "fleco", "fondo", "forma", "fruta", "fuego", "fuera", "gafas", "galas", "prima",
    "ganar", "gente", "globo", "grano", "grito", "grupo", "guapo", "hacha", "harto", "hazlo", "primo",
    "herir", "hielo", "hilos", "honor", "horas", "huevo", "humor", "ideal", "igual", "imita", "promo",
    "indio", "invas", "islas", "joven", "jugar", "junta", "justo", "largo", "lente", "libro", "perra",
    "lindo", "lista", "llama", "llave", "llega", "lleno", "lugar", "luces", "lucha", "salir", "hojas",
    "madre", "magia", "mango", "manos", "marca", "marco", "marea", "matar", "media", "menos", "silla",
    "meses", "metro", "miedo", "mismo", "mitad", "mujer", "mundo", "nacer", "nieve", "niños", "salsa",
    "noble", "noche", "norma", "notas", "nubes", "nuevo", "obras", "ocupa", "ojala", "ojito", "citas",
    "oliva", "ondas", "orden", "oreja", "oruga", "osado", "otros", "ovulo", "padre", "pagar", "solar",
    "palma", "papel", "parar", "parte", "pasar", "pasto", "patio", "peces", "pedir", "pegar", "señal",
    "pelos", "penal", "perro", "pesar", "piano", "picar", "picos", "pieza", "pinta", "plano", "filas",
    "plaza", "pobre", "poder", "poema", "polvo", "poner", "poros", "potes", "presa", "prisa", "cielo",
    "priva", "puede", "punto", "quema", "quien", "quiso", "quiza", "rabia", "rango", "raton", "pizza",
    "rayos", "razon", "recio", "redes", "regla", "reina", "reire", "retos", "rezar", "ricos", "piñas",
    "rifas", "risas", "robar", "rocas", "rodar", "rompe", "ropas", "rosas", "ruido", "rumor", "pilar",
    "saber", "sacar", "salir", "salta", "santo", "sapos", "secar", "selva", "serio", "sirve", "pavos",
    "sobre", "soles", "sonar", "sopla", "suave", "subir", "sueño", "sufre", "susto", "tabla", "motos",
    "tacto", "tarde", "techo", "tener", "tenis", "terco", "tigre", "tinta", "tirar", "tocar", "masas",
    "tomar", "torre", "toser", "traje", "trato", "trigo", "trozo", "tumba", "turno", "unido", "malos",
    "untar", "usado", "usare", "usted", "vacio", "vagar", "valle", "vamos", "vapor", "vasto", "malas",
    "vengo", "verde", "verlo", "verso", "vicio", "video", "viejo", "vigor", "vimos", "vinos", "resos",
    "vista", "vivir", "volar", "votar", "vuelo", "yemas", "yerba", "yerno", "yogur", "zanja", "sismo",
    "zarpa", "zorro", "juega", "gesto", "zorra", "gemas", "tenso", "yegua", "perla", "cinco", "animo",
    "abaco", "abril", "acido", "acoso", "actea", "adios", "adobo", "aguas", "albas", "aleta", "solos",
    "alzar", "ancla", "anexo", "anglo", "anima", "anual", "aorta", "apodo", "ardor", "arfar", "somos",
    "arido", "arpon", "arroz", "asear", "atlas", "atril", "atune", "avaro", "aveza", "axial",
    "etneo", "etolo", "etusa", "evade", "evita", "exodo", "expon", "extra", "fabro", "facer",
    "fagot", "fajar", "falaz", "falda", "fallo", "falsa", "falto", "fanal", "fango", "fante",
    "farad", "fardo", "faros", "farol", "farsa", "fases", "fasto", "fator", "fatuo", "fauna",
    "favor", "faxea", "febeo", "fecal", "fecha", "feliz", "felpa", "felus", "fenix", "feraz",
    "kopek", "kurdo", "labeo", "labia", "labio", "labor", "labra", "lacay", "lacha", "lacio",
    "lacon", "lacre", "ladeo", "ladon", "ladra", "lagar", "lagua", "laico", "laido", "cerca",
    "lamer", "lamia", "lampa", "lanar", "lance", "landa", "lande", "langa", "lanio", "lanza",
    "lapiz", "lapon", "lapsa", "lapso", "laque", "lardo", "larga", "largo", "larra", "larva",
    "lasca", "laser", "lasto", "lataz", "lateo", "latir", "laton", "lauda", "laude", "laudo",
    "launa", "lauro", "lauta", "lavar", "laxar", "layar", "lazar", "lecha", "leche", "lecto",
    "ledon", "leere", "legar", "legon", "legra", "legua", "leila", "leima", "lejas", "lejia",
    "lejio", "lejos", "lembo", "lempa", "lemur", "lenca", "lenon", "lente", "lento", "leona",
    "lepra", "lerda", "lerdo", "lesna", "leste", "letal", "leteo", "leton", "levar", "lexia",
    "leyes", "lezda", "lezna", "liado", "liana", "liara", "liaza", "libar", "libio", "libon",
    "libra", "licio", "licor", "licra", "lider", "lidio", "liego", "lieva", "ligar", "ligio",
    "ligur", "lijar", "lilac", "lilio", "limar", "limbo", "limen", "sopas", "limon", "linao",
    "linar", "lince", "linde", "linea", "linfa", "linio", "linon", "lioso", "lipis", "lipon",
    "liria", "lirio", "liron", "lisis", "lisol", "lista", "listo", "litio", "litis", "litre",
    "litro", "lituo", "liudo", "livor", "llaca", "llaga", "llama", "llana", "llano", "llapa",
    "llave", "lleco", "llega", "llena", "lleno", "llera", "lleta", "lleva", "lloro", "llosa",
    "lobez", "lobos", "local", "locha", "loche", "locro", "lodon", "logar", "palos", "juego",
    "logia", "logis", "logro", "loica", "loina", "loino", "lolio", "lomba", "lombo", "mesas",
    "lomia", "lomos", "lonco", "longa", "longo", "lonja", "lonto", "siete", "lopez", "lorza",
    "losar", "loteo", "lotin", "lucir", "ludio", "ludir", "luego", "lueso", "lugar", "lugre",
    "luisa", "lujar", "lumbo", "lumen", "lumia", "lunar", "luneo", "lunfa", "lupia", "logra",
    "lupus", "lurte", "lusco", "luteo", "luvia", "luxar", "luyir", "mable", "macal", "macar", "luigi",
    "maceo", "macha", "machi", "macho", "macia", "macis", "macla", "macro", "mador", "madre",
    "maeño", "maesa", "maeso", "mafia", "magia", "magin", "magma", "magna", "magra", "magro", "chile",
    "mague", "mahon", "maido", "majal", "majar", "majeo", "malar", "malta", "mamar", "mambo", "prado",
    "mamey", "mamia", "mamon", "mamua", "manal", "manar", "manca", "manco", "manda", "mando", "mudar",
    "manea", "manga", "mango", "mania", "manir", "manso", "manta", "manto", "capas", "gatos", "loros",
    "soñar", "maoma", "maori", "mapas", "maque", "maqui", "marca", "marea", "mareo", "nueve", "carne",
    "marga", "maria", "marra", "marso", "marta", "marte", "marzo", "masar", "masia", "maslo", "asada",
    "mason", "masto", "matar", "mateo", "matiz", "matul", "maula", "maura", "mauro", "mavor", "causa",
    "mayal", "mayar", "mayor", "mazar", "meado", "meaja", "meano", "mecer", "media", "medir", "altos", "talar", "talco",
    "meigo", "mejer", "mejor", "melar", "melca", "melga", "melis", "mella", "melon", "melsa", "arepa", "pesos", "barba",
    "melva", "memez", "menar", "menda", "meneo", "menge", "menor", "menos", "mensu", "menta", "anime", "visto", "gemir",
    "mente", "julio", "junio", "pelar", "siglo", "serie", "seria", "cerro", "plomo", "cobre", "telas", "babas", "violo",
    "casos", "calma", "domar", "palas", "palos", "broma", "meter", "medio", "falla", "evada", "feria", "parir", "pomos",
    "beles", "belez", "belfa", "belfo", "belga", "belio", "bella", "bello", "belua", "bemba", "bembe", "bembo", "bemol",
    "benes", "beoda", "beodo", "beori", "beque", "berbi", "berma", "beron", "berra", "berre", "berro", "berta", "berza",
    "besad", "besan", "besar", "besas", "besen", "beses", "besos", "betas", "betel", "betun", "beuda", "beudo", "beyes",
    "bezar", "bezon", "bezos", "biaza", "bibis", "bical", "bicha", "biche", "bicho", "bicis", "bicos", "bides", "bidon",
    "biela", "bifaz", "bifes", "bigas", "bijao", "bijas", "bijol", "bilao", "biles", "bilis", "billa", "bilma", "bilme",
    "bilmo", "bimba", "binad", "binan", "binar", "binas", "binea", "binee", "binen", "bineo", "bines", "bingo", "binza",
    "biota", "biras", "birla", "birle", "birli", "birlo", "biros", "bisad", "bisan", "bisar", "bisas", "bisel", "bisen",
    "bises", "bisos", "biste", "bitad", "bitan", "bitar", "bitas", "biten", "biter", "bites", "bitor", "bizas", "bizca",
    "bizco", "bizma", "bizme", "bizmo", "bizna", "blaos", "blava", "blavo", "bleda", "bledo", "bloca", "bloco", "blocs",
    "boque", "boqui", "borax", "borda", "borde", "bordo", "boreo", "boria", "borla", "borna", "borne", "borni", "boros",
    "borra", "borre", "borro", "borto", "bosar", "boson", "bosta", "botad", "botan", "botar", "botas", "botea", "botee",
    "boten", "boteo", "botes", "botin", "boton", "botor", "botos", "boxea", "boxee", "boxeo", "boxer", "boxes", "boyad",
    "boyal", "boyan", "boyar", "boyas", "boyen", "boyes", "bozal", "bozas", "bozon", "bozos", "braca", "braco", "braga",
    "brama", "brame", "bramo", "brana", "brasa", "brava", "bravo", "braza", "brazo", "bread", "brean", "brear", "breas",
    "breca", "brece", "breco", "breen", "brees", "brega", "brego", "brena", "brete", "breva", "breve", "breza", "brezo",
    "brial", "briba", "brice", "brida", "briol", "brios", "brisa", "brise", "briso", "bufes", "bufet", "bufia", "bufon",
    "bufos", "bugle", "buhio", "buhos", "buida", "buido", "bujeo", "bujes", "bujia", "bujos", "bular", "bulas", "bulbo",
    "bulda", "bules", "bulin", "bulis", "bulla", "bulle", "bulli", "bullo", "bulon", "bulos", "bulto", "bunas", "bunio",
    "buque", "buras", "burda", "burdo", "burel", "bureo", "burga", "burgo", "buril", "burio", "buris", "burla", "burle",
    "burlo", "buros", "burra", "burro", "busca", "busco", "buses", "busto", "buten", "butia", "buyos", "buzad", "buzan",
    "buzar", "buzas", "buzon", "buzos", "cabal", "cabas", "cabed", "caben", "caber", "cabes", "cabia", "cabio", "cable",
    "cabos", "cabra", "cabre", "cabro", "cacan", "cacao", "cacas", "cacea", "cacee", "cacen", "caceo", "caces", "cacha",
    "cache", "cacho", "cachu", "cacle", "cacos", "cacto", "cacuy", "cadas", "cadis", "cados", "caeis", "caena", "caera",
    "caere", "cafes", "cafiz", "cafre", "cagad", "cagan", "cagar", "cagas", "cagon", "cague", "cahiz", "caian", "caias",
    "caico", "caida", "caido", "caies", "caiga", "caigo", "caima", "caire", "caite", "cajas", "cajel", "cajin", "cajis",
    "cajon", "cajos", "calad", "calan", "calao", "calar", "calas", "calca", "calce", "calco", "calda", "caldo", "caled",
    "calen", "caler", "cales", "calia", "calio", "calis", "caliz", "calla", "calle", "callo", "calma", "calme", "calmo",
    "calon", "calor", "calos", "calta", "calva", "calve", "calvo", "calza", "calzo", "camal", "camao", "camas", "camba",
    "cambe", "cambo", "citar", "mirar", "nariz", "civil", "culpa", "digna", "dolar", "ducto", "ducha", "epico", "facto"
];